name: CD

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-Latest
    steps:
      - name : code checkout
        uses: actions/checkout@v4
      - name: build
        uses: appleboy/ssh-action@v1.2.5
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ubuntu
          script: |
            cd ~/DevOps
            git pull origin main
            sudo docker compose up -d --build